branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.8

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

before_cache:
  # Cleanup to avoid the cache to grow indefinitely as new package versions are released
  # see https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
  - brew cleanup

cache:
  directories:
    # Cache downloaded bottles
    - $HOME/Library/Caches/Homebrew
    # pyenv
    - $HOME/.pyenv_cache
    - $HOME/.pyenv/versions/3.7.8
    - $HOME/.pyenv/versions/2.7.15
    # scikit-ci-addons
    - $HOME/downloads

before_install:
  - |
    # Workaround the following error occuring because python installation is cached but gettext dependency is not
    #   dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    #     Referenced from: /Users/travis/.pyenv/versions/3.7.2/bin/python
    #     Reason: Incompatible library version: python requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
    if [[ "$TRAVIS_OS_NAME" == "osx" && "${PYTHON_VERSION}" == "3.7.8" ]]; then
      brew install gettext
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test

deploy:
  # deploy-release
  - provider: script
    script: pwd && ls dist;echo "deploy-release" && ~/.pyenv/versions/${PYTHON_VERSION}/bin/twine upload -u __token__ -p $PYPI_PASSWORD --skip-existing dist/*
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
  # deploy-master
  - provider: script
    script: pwd && ls dist;echo "deploy-master" && echo "not implemented"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master

env:
  global:
    # PYPI_PASSWORD
    - secure: "KGHel2nKEcPM6VAYgBdwPEKghrUfylvtAXsXm2kjxzTT2zCiOYWTy0pb1grKlvcasRcvSViuiGL6x/tyTT2mh5Qf74S5WgIbgo2VEFIP9XekNRiYFOp4UEfup0Roa4tL3Yvb+xkcF5kIe4mhf4hddAweJN0KWZt+Vk6Q6udJ4c+WyIWFaXIpl1/QyAeGs6tSpYKQiE40aGUYcRgKrZf1ydPqLJ1SKul13nurnZ3CsH7GcezsVbmdV0QvUcfPwefMSO+pMMMirQmKj977dPRz7CI0hlw0sJTGIOLxHIQNYBMBYu6G81yjyNHh2BKjAXv7V4K5Rc9TmCdAQYSmkhRQVBsaLxIYMuux5w8ms+ldd0oXd38UoFLhZyu4QZBAROEsTRPWLugzsJWgPJRQazv2ENZE5QykzIMJJf4VpTGWQfhbCgUA7GIHUYYKFiJ6Jr33Fzv1HKVhUabSB2yWYiMYoy54rosvxiwSacrC0aWEFGiB9D6sbEQ9rKdHY2ivmT1u/iFw+Qb59uaWy0lm1qoYiLbBt5tpJr5epdc+rOo9i0QB81KhU7/4Hf4kr+QRGxIp/jXEpbrKqgG6YCTzxEMZ2PV3uzV2Z3ZUqupRdcihmouhy7TnbIG7vhm7fVtold9Wwmoiv46/FT2v0EjjiMunhgEhk7t5Lia+qwJgPzrx5xw="
